name: Checking release branch exist
runs-on: ubuntu-latest
steps:
  - name: Checking user input parameters 
    run: |
      # Ensure origin is correctly set
      git remote -v || (echo "Error: No remote repository found." && exit 1)

      # Try fetching the remote branches and check if the specific branch exists
      if git ls-remote --heads origin "${{ github.event.inputs.build_origin_branch }}" | awk '{print $2}' | grep -q "refs/heads/${{ github.event.inputs.build_origin_branch }}"; then
        echo "Found ${{ github.event.inputs.build_origin_branch }} on remote"
      else 
        echo "Error: ${{ github.event.inputs.build_origin_branch }} not found on remote"
        exit 1
      fi