name: Set up branches based on checkmark input
runs-on: ubuntu-latest
steps:
  - name: Set up branches based on checkmark input
    id: set_branches
    run: |
      echo "Validating checkmark set"
      if [ "${{ github.event.inputs.main_checkmark }}" == "true" ]; then
        echo "Building from main branches"
        echo "CLIENT1_BRANCH=main" >> $GITHUB_ENV
        echo "CLIENT2_BRANCH=main" >> $GITHUB_ENV
        echo "RELEASE_BRANCH=main" >> $GITHUB_ENV
      else
        echo "Error: checkmark was not set"
        exit 1
      fi
