name: 'Validate build origin branch'
description: 'Verify that specified branch exists for build origin'

inputs:
  build_origin_branch:
    description: 'Set build origin branch'
    required: true

runs:
  using: "composite"  
  steps:
    - name: Ensure origin is correctly set
      run: |
        git remote -v || (echo "Error: No remote repository found." && exit 1)
        # Try fetching the remote branches and check if the specific branch exists
        if git ls-remote --heads origin "${{ inputs.build_origin_branch }}" | awk '{print $2}' | grep -q "refs/heads/${{ inputs.build_origin_branch }}"; then
          echo "Found ${{ inputs.build_origin_branch }} on remote"
        else 
          echo "Error: ${{ inputs.build_origin_branch }} not found on remote"
          exit 1
        fi
      shell: bash
