name: 'Check User Input'
description: 'Checks if the specified release branch exists on the remote'

inputs:
  build_origin_branch:
    description: 'The branch to check for existence'
    required: true

runs:
  using: "composite"  
  steps:
    - name: Checking user input parameters
      run: |
        # Ensure origin is correctly set
        git remote -v || (echo "Error: No remote repository found." && exit 1)

        # Try fetching the remote branches and check if the specific branch exists
        if git ls-remote --heads origin "${{ inputs.build_origin_branch }}" | awk '{print $2}' | grep -q "refs/heads/${{ inputs.build_origin_branch }}"; then
          echo "Found ${{ inputs.build_origin_branch }} on remote"
        else 
          echo "Error: ${{ inputs.build_origin_branch }} not found on remote"
          exit 1
        fi
      shell: bash  # Specify the shell
