name: Validate specified release branch compliance
description: Validate release branch main/master or other non-existing branch
inputs:
    release_branch:
     description: 'Set desired release branch'
     required: true  
runs:
    using: "composite"
    steps:
      - name: Confirm release branch compliance
        run: |
              # Check if the release branch is main or master
              echo "Validate specified release branch compliance"
              if [[ "${{ inputs.release_branch }}" == "main" ]] || [[ "${{ inputs.release_branch }}" == "master" ]]; then
                echo "Skip validation for main/master branch"
              else
                # Ensure the branch doesn't already exist on the remote to prevent accidental overwrite
                if git ls-remote --heads origin "${{ github.event.inputs.release_branch }}" | awk '{print $2}' | grep -q "refs/heads/${{ inputs.release_branch }}"; then
                  echo "${{ inputs.release_branch }} already exists on remote, creation not allowed."
                  exit 1
                else
                  echo "${{ inputs.release_branch }} does not exist on remote, creation allowed."
                fi
              fi
        shell: bash