name: Set up branches based on checkmark input
description: Default dependant branches to main
inputs:
    main_checkmark:
        description: Checkmark set
        required: true
runs:
    using: "composite"
    steps:
      - name: Set up branches based on checkmark input
        run: |
          echo "Validating checkmark set"
          if [ "${{ inputs.main_checkmark }}" == "true" ]; then
            echo "Building from main branches"
            echo "CLIENT1_BRANCH='main'" >> $GITHUB_ENV
            echo "CLIENT2_BRANCH='main'" >> $GITHUB_ENV
            echo "RELEASE_BRANCH='main'" >> $GITHUB_ENV
          else
            echo "Error: checkmark was not set"
            exit 1
          fi
        shell: bash