name: Checkout submodules
description: Checkout for client1 and client2
inputs:
  github_token:
    description: 'token for authentification'
    required: true

  client1_branch:
    description: 'Checkout fot client1 repo'
    required: true
  
  client2_branch:
    description: 'Checkout fot client2 repo'
    required: true
runs:
    using: "composite"
    steps:
      - name: Checkout submodule client1
        uses: actions/checkout@v4
        with:
          token: '${{ inputs.github_token }}'
          repository: illyazhuk/client1
          path: default/procentric/app/client1
          ref: ${{ inputs.client1_branch }}
        shell: bash  # Specify the shell

      - name: Checkout submodule client2
        uses: actions/checkout@v4
        with:
          token: '${{ inputs.github_token }}'
          repository: illyazhuk/client2
          path: default/remote/client2
          ref: ${{ inputs.client2_branch }}
        shell: bash  # Specify the shell