name: Checkout submodules
runs:
    using: "composite"
    shell: bash  # Specify the shell
    steps:
      - name: Checkout submodule client1
        uses: actions/checkout@v4
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          repository: illyazhuk/client1
          path: default/procentric/app/client1
          ref: ${{ env.CLIENT1_BRANCH }}

      - name: Checkout submodule client2
        uses: actions/checkout@v4
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          repository: illyazhuk/client2
          path: default/remote/client2
          ref: ${{ env.CLIENT2_BRANCH }}
