name: Release default
on:
  workflow_dispatch:
    inputs:
      main_checkmark:
        description: 'Build from main branches'
        default: false
        type: boolean
        required: true
      release_version:
        description: 'Enter the release version (e.g. v1.2.3)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout origin (ci-cd-main) repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all branches and history are fetched

      - name: Set up branches based on checkmark input
        id: set_branches
        uses: ./steps/set_up_branches_checkmark.yml

      - name: Checkout submodules
        uses: ./steps/checkout_submodules.yml

      - name: Checkout to a new branch
        uses: ./steps/chrckout_to_new_branch.yml

      - name: Commit updated submodule pointers
        uses: ./steps/commit_updated_submodule_pointers.yml

      - name: manage-release-version
        uses: ./steps/manage_release_version.yml 

      - name: Push changes to target branch
        uses: ./steps/push_changes.yml
    
      - name: Create and push release tag
        uses: ./steps/create_release_tag.yml


