name: Release custom

on:
  workflow_dispatch:
    inputs:
      build_origin_branch:
        description: 'Enter origin branch (CI-CD-main repo)'
        required: true
        default: 'main'
      release_version:
        description: 'Enter the release version (e.g. v1.2.3)'
        required: true
      client1_branch:
        description: 'Branch for client1 (default: main)'
        required: true
        default: 'main'
      client2_branch:
        description: 'Branch for client2 (default: main)'
        required: true
        default: 'main'
      release_branch:
        description: 'Branch for where to release (default: main)'
        required: true
        default: 'main'


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout origin (ci-cd-main) repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all branches and history are fetched

      - name: Checking user input parameters
        uses: ./.github/actions/check_user_input
        with: 
            build_origin_branch: ${{ github.event.inputs.build_origin_branch }}

      - name: Checking if target branch exist
        uses: ./.github/actions/check_branch_exist
        with: 
            remote_repository_url: "https://api.github.com/repos/illyazhuk/client1/branches"
            target_branch: ${{ github.event.inputs.client1_branch }}
            github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checking if target branch exist
        uses: ./.github/actions/check_branch_exist
        with: 
            remote_repository_url: "https://api.github.com/repos/illyazhuk/client2/branches"
            target_branch: ${{ github.event.inputs.client2_branch }}
            github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if release branch already exists
        uses: ./.github/actions/check_release_branch_exist 
        with:
             release_branch: ${{ github.event.inputs.release_branch }}

      - name: Validate and check release version
        uses: ./.github/actions/validate_release_version 
        with:
             release_version: ${{ github.event.inputs.release_version }}

      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      - name: Checkout to a new branch
        uses: ./.github/actions/checkout_to_new_branch
        with:
             release_branch: ${{ github.event.inputs.release_branch }}
            
      - name: Checkout submodules
        uses: ./.github/actions/checkout_submodules
        with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
             client1_branch: ${{ github.event.inputs.client1_branch }}
             client2_branch: ${{ github.event.inputs.client2_branch }}

      - name: Commit updated submodule pointers
        uses: ./.github/actions/commit_updated_submodule_pointers
        with: 
             github_user_email: "actions@github.com"
             github_username: "GitHub Actions"
            
      - name: Push changes to target branch
        uses: ./.github/actions/push_changes
        with:
             release_branch: ${{ github.event.inputs.release_branch }}

      - name: Create and push release tag
        uses: ./.github/actions/create_release_tag
        with:
             release_branch: ${{ github.event.inputs.release_branch }}
             release_tag: $RELEASE_VERSION #${{ github.event.inputs.release_version }}

