name: Release default
on:
  workflow_dispatch:
    inputs:
      main_checkmark:
        description: 'Build from main branches'
        default: false
        type: boolean
        required: true
      release_version:
        description: 'Enter the release version (e.g. 1.2.3)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout origin (ci-cd-main) repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all branches and history are fetched

      - name: Set up branches based on checkmark input
        uses: ./.github/actions/set_up_branches_checkmark
        with:
             main_checkmark: ${{ github.event.inputs.main_checkmark }}

      - name: Checkout origin submodules
        uses: ./.github/actions/checkout_submodules
        with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
             client1_branch: ${{ env.CLIENT1_BRANCH }}
             client2_branch: ${{ env.CLIENT2_BRANCH }}

      - name: Commit updated submodule pointers
        uses: ./.github/actions/update_submodule_pointers
        with: 
             github_user_email: "actions@github.com"
             github_username: "GitHub Actions"

      - name: Manage release version
        uses: ./.github/actions/manage_release_version
        with: 
             release_version: ${{ github.event.inputs.release_version }}

      - name: Update release branch
        uses: ./.github/actions/update_release_branch
        with:
             release_branch: ${{ env.RELEASE_BRANCH }}
    
      - name: Set release tag
        uses: ./.github/actions/set_release_tag
        with:
             release_branch: ${{ env.RELEASE_BRANCH }}

