name: Release custom

on:
  workflow_dispatch:
    inputs:
      build_origin_branch:
        description: 'Enter origin branch (CI-CD-main repo)'
        required: true
        default: 'main'
      release_version:
        description: 'Enter the release version (e.g. v1.2.3)'
        required: true
      client1_branch:
        description: 'Branch for client1 (default: main)'
        required: true
        default: 'main'
      client2_branch:
        description: 'Branch for client2 (default: main)'
        required: true
        default: 'main'
      release_branch:
        description: 'Branch for where to release (default: main)'
        required: true
        default: 'main'


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout origin (ci-cd-main) repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all branches and history are fetched

      - name: Checking user input parameters
        uses: ./.github/actions/check_user_input
        with: 
            build_origin_branch: ${{ github.event.inputs.build_origin_branch }}

      - name: Checking if target branch exists
        uses: ./.github/actions/check_branch_exists
        with: 
            remote_repository_url: "https://api.github.com/repos/illyazhuk/client1/branches"
            target_branch: ${{ github.event.inputs.client1_branch }}

      - name: Target branch selection
        run: |
          $REMOTE_REPOSITORY_URL="https://api.github.com/repos/illyazhuk/client2/branches"
          $TARGET_BRANCH=${{ github.event.inputs.client2_branch }}

      - name: Checking if target branch exists
        uses: ./.github/actions/check_branch_exists

      - name: Check if release branch already exists
        uses: ./.github/actions/check_release_branch_exist 

      - name: Validate and check release version
        uses: ./.github/actions/validate_release_version 

      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      - name: Checkout to a new branch
        uses: ./.github/actions/checkout_to_new_branch
            
      - name: Checkout submodules
        uses: ./.github/actions/checkout_submodules

      - name: Commit updated submodule pointers
        uses: ./.github/actions/commit_updated_submodule_pointers

      - name: Push changes to target branch
        uses: ./.github/actions/push_changes

      - name: Create and push release tag
        uses: ./.github/actions/create_release_tag